"""
Offline backup question bank (25 skills x 10 questions).
Format: (question, correct_answer, wrong1, wrong2, wrong3, level)
Used ONLY when Gemini is overloaded/unavailable. Gemini-generated questions are
also cached in the database and grow this bank automatically.
"""

SEED = {
"Python": [
 ("Which keyword is used to define a function in Python?", "def", "func", "function", "define", "easy"),
 ("What is the output of len([1, 2, 3])?", "3", "2", "4", "Error", "easy"),
 ("Which data type is immutable in Python?", "tuple", "list", "dict", "set", "easy"),
 ("What does the 'pip' command do?", "Installs Python packages", "Runs a Python file", "Compiles Python code", "Opens the interpreter", "easy"),
 ("What is a list comprehension?", "A concise way to create lists from iterables", "A method to sort a list", "A way to import lists", "A list of comments", "medium"),
 ("What does '__init__' do in a class?", "Initialises a new object", "Deletes an object", "Imports a module", "Defines a static method", "medium"),
 ("What does the 'yield' keyword create?", "A generator", "A thread", "A class", "A decorator", "medium"),
 ("What is the result of bool([])?", "False", "True", "None", "Error", "medium"),
 ("What does the GIL in CPython do?", "Allows only one thread to execute bytecode at a time", "Speeds up multiprocessing", "Manages garbage collection only", "Locks files on disk", "hard"),
 ("What is the output of [x*x for x in range(3)]?", "[0, 1, 4]", "[1, 4, 9]", "[0, 1, 2]", "[0, 2, 4]", "hard"),
],
"Java": [
 ("Which keyword is used to inherit a class in Java?", "extends", "implements", "inherits", "super", "easy"),
 ("What is the entry point method of a Java program?", "public static void main(String[] args)", "start()", "run()", "init()", "easy"),
 ("Which of these is NOT a primitive type in Java?", "String", "int", "boolean", "char", "easy"),
 ("What does JVM stand for?", "Java Virtual Machine", "Java Variable Method", "Joint Virtual Memory", "Java Visual Manager", "easy"),
 ("Which keyword prevents a method from being overridden?", "final", "static", "abstract", "const", "medium"),
 ("What is the difference between '==' and equals() for Strings?", "== compares references, equals() compares content", "They are identical", "== compares content, equals() compares references", "equals() works only on numbers", "medium"),
 ("Which collection does NOT allow duplicate elements?", "HashSet", "ArrayList", "LinkedList", "Vector", "medium"),
 ("What is an interface in Java?", "A contract of abstract methods a class can implement", "A concrete class", "A type of loop", "A package", "medium"),
 ("What does the 'volatile' keyword guarantee?", "Visibility of variable changes across threads", "Atomic increment operations", "Faster execution", "Automatic locking", "hard"),
 ("Which garbage collection concept marks objects unreachable from GC roots?", "Mark-and-sweep", "Reference swapping", "Heap folding", "Stack unwinding", "hard"),
],
"C++": [
 ("Which operator is used to access a member through a pointer in C++?", "->", ".", "::", "&", "easy"),
 ("Which header is needed for cout?", "<iostream>", "<stdio.h>", "<stdlib.h>", "<string>", "easy"),
 ("What is the size of 'char' in C++ (typically)?", "1 byte", "2 bytes", "4 bytes", "8 bytes", "easy"),
 ("Which keyword is used to allocate memory dynamically?", "new", "malloc_new", "alloc", "create", "easy"),
 ("What is a reference in C++?", "An alias for an existing variable", "A copy of a variable", "A null pointer", "A type of array", "medium"),
 ("What is a virtual function used for?", "Runtime polymorphism", "Compile-time optimisation", "Memory allocation", "Operator overloading", "medium"),
 ("What does RAII stand for?", "Resource Acquisition Is Initialization", "Random Access Instruction Interface", "Runtime Allocated Integer Index", "Reference And Instance Initialization", "medium"),
 ("Which STL container stores unique sorted keys?", "std::set", "std::vector", "std::list", "std::deque", "medium"),
 ("What does std::move do?", "Casts an object to an rvalue reference", "Copies memory", "Deletes an object", "Swaps two pointers", "hard"),
 ("Which smart pointer allows shared ownership?", "std::shared_ptr", "std::unique_ptr", "std::auto_ptr", "std::raw_ptr", "hard"),
],
"JavaScript": [
 ("Which keyword declares a block-scoped variable?", "let", "var", "def", "dim", "easy"),
 ("What is typeof null in JavaScript?", "object", "null", "undefined", "number", "easy"),
 ("Which method adds an element to the end of an array?", "push()", "pop()", "shift()", "unshift()", "easy"),
 ("What does '===' check?", "Value and type equality", "Only value equality", "Only type equality", "Reference assignment", "easy"),
 ("What is a closure?", "A function that remembers variables from its outer scope", "A function with no name", "A way to close the browser", "A loop construct", "medium"),
 ("What does Promise.all do?", "Waits for all promises to resolve", "Returns the first resolved promise", "Cancels promises", "Runs promises sequentially", "medium"),
 ("What is event bubbling?", "Events propagate from child to parent elements", "Events propagate from parent to child", "Events are cancelled", "Events repeat forever", "medium"),
 ("What does 'this' refer to inside an arrow function?", "The lexical (enclosing) this", "The global object always", "The function itself", "undefined always", "medium"),
 ("In what order do microtasks and macrotasks run?", "Microtasks run before the next macrotask", "Macrotasks run first always", "They run in parallel", "Random order", "hard"),
 ("What is the output of console.log(0.1 + 0.2 === 0.3)?", "false", "true", "NaN", "undefined", "hard"),
],
"TypeScript": [
 ("What is TypeScript?", "A typed superset of JavaScript", "A database", "A CSS framework", "A Python library", "easy"),
 ("Which file configures the TypeScript compiler?", "tsconfig.json", "package.json", "webpack.config.js", "ts.config.xml", "easy"),
 ("How do you declare a number variable in TypeScript?", "let x: number = 5;", "let x = number(5);", "number x = 5;", "var x as number = 5;", "easy"),
 ("What does the 'any' type do?", "Disables type checking for that value", "Accepts only strings", "Creates a union type", "Marks a value optional", "easy"),
 ("What is an interface used for?", "Describing the shape of an object", "Looping over arrays", "Importing modules", "Handling errors", "medium"),
 ("What does the '?' in 'name?: string' mean?", "The property is optional", "The property is private", "The property is readonly", "The property is a promise", "medium"),
 ("What is a union type?", "A value that can be one of several types", "A merge of two classes", "A type for arrays only", "A type for enums only", "medium"),
 ("What does 'readonly' do on a property?", "Prevents reassignment after initialisation", "Hides the property", "Makes it async", "Deletes it at runtime", "medium"),
 ("What does the 'keyof' operator return?", "A union of an object type's keys", "The values of an object", "The length of an array", "The class name", "hard"),
 ("What is a generic?", "A reusable component that works over multiple types", "A default export", "A global variable", "A decorator for classes only", "hard"),
],
"HTML_CSS": [
 ("Which HTML tag creates a hyperlink?", "<a>", "<link>", "<href>", "<url>", "easy"),
 ("Which CSS property changes text colour?", "color", "font-style", "text-decoration", "background", "easy"),
 ("Which tag holds the main heading of highest level?", "<h1>", "<head>", "<header1>", "<title>", "easy"),
 ("What does CSS stand for?", "Cascading Style Sheets", "Creative Style System", "Computer Style Sheets", "Colorful Style Syntax", "easy"),
 ("Which CSS display value enables flexbox?", "flex", "block", "inline", "table", "medium"),
 ("What is the CSS box model order from inside out?", "content, padding, border, margin", "margin, border, padding, content", "content, border, padding, margin", "padding, content, margin, border", "medium"),
 ("What does semantic HTML mean?", "Using tags that describe their meaning, e.g. <nav>, <article>", "Using only <div> tags", "Using inline styles", "Writing HTML in lowercase", "medium"),
 ("What does 'position: absolute' position relative to?", "The nearest positioned ancestor", "The viewport always", "The previous sibling", "The document title", "medium"),
 ("Which media feature is used for responsive layouts?", "@media (max-width: ...)", "@responsive", "@screen-size", "@layout", "hard"),
 ("What does z-index control?", "Stacking order of positioned elements", "Zoom level", "Font size", "Element width", "hard"),
],
"React": [
 ("What is JSX?", "A syntax extension that looks like HTML inside JavaScript", "A database language", "A CSS preprocessor", "A testing tool", "easy"),
 ("Which hook manages state in a function component?", "useState", "useFetch", "useClass", "useRender", "easy"),
 ("How do you pass data from parent to child components?", "props", "state", "refs", "reducers only", "easy"),
 ("What does React use to efficiently update the DOM?", "Virtual DOM", "Shadow tree", "Direct DOM rewrite", "Server polling", "easy"),
 ("When does useEffect with an empty dependency array run?", "Once after the first render", "On every render", "Never", "Before render", "medium"),
 ("Why are 'key' props used in lists?", "To help React identify which items changed", "To style list items", "To sort the list", "To encrypt data", "medium"),
 ("What is lifting state up?", "Moving shared state to the closest common parent", "Moving state to localStorage", "Deleting state", "Using global variables", "medium"),
 ("Which hook memoises an expensive computed value?", "useMemo", "useRef", "useContext", "useId", "medium"),
 ("What problem does React Context solve?", "Avoiding prop drilling", "Routing", "Server-side rendering", "Form validation", "hard"),
 ("What happens if you mutate state directly?", "React may not re-render correctly", "React throws a compile error", "State is deleted", "It always works fine", "hard"),
],
"SQL": [
 ("Which SQL statement retrieves data?", "SELECT", "GET", "FETCH", "PULL", "easy"),
 ("Which clause filters rows?", "WHERE", "ORDER BY", "GROUP BY", "LIMIT", "easy"),
 ("Which keyword removes duplicate rows in a result?", "DISTINCT", "UNIQUE ROWS", "REMOVE", "SINGLE", "easy"),
 ("What does PRIMARY KEY guarantee?", "Unique, non-null identifier per row", "Allows duplicates", "Allows nulls", "Sorts the table", "easy"),
 ("Which JOIN returns all rows from the left table and matching rows from the right?", "LEFT JOIN", "INNER JOIN", "CROSS JOIN", "SELF JOIN", "medium"),
 ("Which function counts rows?", "COUNT()", "SUM()", "TOTAL()", "ROWS()", "medium"),
 ("What does GROUP BY do?", "Groups rows sharing values so aggregates can be applied", "Sorts rows", "Deletes rows", "Joins tables", "medium"),
 ("Difference between WHERE and HAVING?", "HAVING filters groups after aggregation", "They are identical", "WHERE filters groups", "HAVING filters columns", "medium"),
 ("What is database normalisation?", "Organising data to reduce redundancy", "Encrypting data", "Backing up data", "Indexing every column", "hard"),
 ("What does an index do?", "Speeds up lookups at the cost of extra storage and write time", "Deletes old rows", "Encrypts a column", "Merges two tables", "hard"),
],
"NoSQL": [
 ("Which of these is a document database?", "MongoDB", "MySQL", "PostgreSQL", "Oracle", "easy"),
 ("What format does MongoDB store documents in internally?", "BSON", "CSV", "XML", "YAML", "easy"),
 ("Which NoSQL type is Redis primarily?", "Key-value store", "Graph database", "Column-family only", "Relational", "easy"),
 ("What is a typical benefit of NoSQL?", "Flexible schema and horizontal scaling", "Mandatory joins", "Fixed schema", "Only vertical scaling", "easy"),
 ("Which database is a graph database?", "Neo4j", "Redis", "Cassandra", "SQLite", "medium"),
 ("What does the CAP theorem state?", "A distributed system cannot guarantee all of Consistency, Availability, Partition tolerance together", "Databases must be relational", "Caches must be consistent", "SQL beats NoSQL", "medium"),
 ("What is sharding?", "Splitting data across multiple machines", "Backing up data", "Encrypting data", "Joining collections", "medium"),
 ("Cassandra is best described as a:", "Wide-column store", "Document store", "Graph store", "In-memory cache only", "medium"),
 ("What does eventual consistency mean?", "Replicas converge to the same value given time without new updates", "Writes are always instantly visible everywhere", "Data is never replicated", "Reads are blocked until all writes finish", "hard"),
 ("In MongoDB, what is an aggregation pipeline?", "A series of stages that transform documents", "A backup tool", "A network protocol", "A user role", "hard"),
],
"Cloud_Computing": [
 ("What does IaaS stand for?", "Infrastructure as a Service", "Internet as a Service", "Integration as a System", "Instance and Storage", "easy"),
 ("Which is a major public cloud provider?", "Amazon Web Services", "Linux", "Docker", "GitHub", "easy"),
 ("What is object storage in AWS called?", "S3", "EC2", "RDS", "Lambda", "easy"),
 ("What is a benefit of cloud elasticity?", "Resources scale up and down with demand", "Fixed capacity", "No internet needed", "Free unlimited usage", "easy"),
 ("What is serverless computing?", "Running code without managing servers", "Computing without electricity", "Using no databases", "On-premise hosting", "medium"),
 ("What is a virtual private cloud (VPC)?", "A logically isolated network in the cloud", "A physical data centre", "A type of database", "A billing plan", "medium"),
 ("What does auto-scaling do?", "Adjusts the number of instances automatically", "Encrypts traffic", "Backs up volumes", "Creates users", "medium"),
 ("What is a region vs an availability zone?", "A region contains multiple isolated availability zones", "They are the same", "An AZ contains many regions", "Regions are only for billing", "medium"),
 ("What is the shared responsibility model?", "Provider secures the cloud; customer secures what they put in it", "Provider secures everything", "Customer secures everything", "Only the government secures it", "hard"),
 ("Which service model gives you only a runtime to deploy code (no OS management)?", "PaaS", "IaaS", "On-prem", "Colocation", "hard"),
],
"DevOps": [
 ("What does CI/CD stand for?", "Continuous Integration / Continuous Delivery", "Code Inspection / Code Deployment", "Central Integration / Central Development", "Continuous Input / Continuous Debugging", "easy"),
 ("Which tool is used to containerise applications?", "Docker", "Git", "Jenkins", "Nginx", "easy"),
 ("What is Infrastructure as Code?", "Managing infrastructure through machine-readable files", "Writing code on servers manually", "Buying hardware", "A programming language", "easy"),
 ("Which tool is commonly used for infrastructure as code?", "Terraform", "Photoshop", "Excel", "Slack", "easy"),
 ("What does Kubernetes do?", "Orchestrates containers at scale", "Compiles code", "Stores source code", "Writes tests", "medium"),
 ("What is a Docker image?", "A read-only template used to create containers", "A running process", "A virtual machine disk", "A log file", "medium"),
 ("What is blue-green deployment?", "Running two environments and switching traffic between them", "Colour-coding logs", "A testing language", "A branching strategy", "medium"),
 ("What does a CI pipeline typically run?", "Build and automated tests on each commit", "Manual approvals only", "Database backups only", "Hardware inspection", "medium"),
 ("What is the purpose of monitoring tools such as Prometheus?", "Collect metrics and alert on system health", "Compile code", "Host Git repos", "Design UIs", "hard"),
 ("What is a Kubernetes Pod?", "The smallest deployable unit, one or more containers", "A cluster node", "A storage volume", "A load balancer", "hard"),
],
"DSA": [
 ("Which data structure follows LIFO?", "Stack", "Queue", "Array", "Heap", "easy"),
 ("What is the time complexity of binary search?", "O(log n)", "O(n)", "O(n log n)", "O(1)", "easy"),
 ("Which data structure follows FIFO?", "Queue", "Stack", "Tree", "Graph", "easy"),
 ("What is the average lookup time of a hash table?", "O(1)", "O(n)", "O(log n)", "O(n^2)", "easy"),
 ("Which traversal of a BST gives sorted order?", "Inorder", "Preorder", "Postorder", "Level order", "medium"),
 ("What is the worst-case time of quicksort?", "O(n^2)", "O(n log n)", "O(n)", "O(log n)", "medium"),
 ("Which algorithm finds the shortest path in a graph with non-negative weights?", "Dijkstra's", "DFS", "Kruskal's", "Prim's", "medium"),
 ("What data structure is typically used for BFS?", "Queue", "Stack", "Heap", "Trie", "medium"),
 ("What is dynamic programming?", "Solving problems by storing results of overlapping subproblems", "Writing code at runtime", "Using dynamic typing", "Randomised algorithms", "hard"),
 ("What is the time complexity of building a binary heap from n items (heapify)?", "O(n)", "O(n log n)", "O(log n)", "O(n^2)", "hard"),
],
"Machine_Learning": [
 ("Which type of learning uses labelled data?", "Supervised learning", "Unsupervised learning", "Reinforcement learning only", "Transfer-free learning", "easy"),
 ("What is overfitting?", "Model performs well on training data but poorly on new data", "Model is too small", "Model never trains", "Model has no features", "easy"),
 ("Which algorithm is used for classification and uses a sigmoid function?", "Logistic regression", "Linear regression", "K-means", "PCA", "easy"),
 ("What does K-means do?", "Clusters data into k groups", "Predicts prices", "Labels images", "Reduces labels", "easy"),
 ("What is the purpose of a train/test split?", "Evaluate the model on unseen data", "Speed up training", "Remove outliers", "Encode categories", "medium"),
 ("Which metric is best when classes are highly imbalanced?", "F1-score / precision-recall", "Accuracy only", "Mean squared error", "R-squared", "medium"),
 ("What is regularisation?", "A technique to reduce overfitting by penalising complexity", "Scaling features", "Collecting more rows", "Increasing learning rate", "medium"),
 ("What does a Random Forest combine?", "Many decision trees", "Many neural networks", "Many clusters", "Many regressions of one variable", "medium"),
 ("What is the bias-variance tradeoff?", "Balancing underfitting (bias) and overfitting (variance)", "Choosing a GPU", "Picking a dataset size", "Selecting a language", "hard"),
 ("What does cross-validation do?", "Estimates model performance by rotating train/validation folds", "Encrypts the dataset", "Increases dataset size", "Removes features", "hard"),
],
"Deep_Learning": [
 ("What is a neuron's activation function used for?", "Introducing non-linearity", "Storing data", "Reducing dataset size", "Sorting inputs", "easy"),
 ("Which network type is commonly used for images?", "CNN", "Decision tree", "Linear SVM", "K-NN", "easy"),
 ("What algorithm updates weights in neural networks?", "Backpropagation with gradient descent", "Binary search", "Merge sort", "Hashing", "easy"),
 ("Which framework is developed by Google for deep learning?", "TensorFlow", "Flask", "Django", "Pandas", "easy"),
 ("What problem do LSTMs mainly address?", "Vanishing gradients in sequences", "Image resizing", "Data labelling", "Feature scaling", "medium"),
 ("What is dropout?", "Randomly disabling neurons during training to reduce overfitting", "Deleting the dataset", "Stopping training early only", "Increasing layers", "medium"),
 ("What does ReLU compute?", "max(0, x)", "1/(1+e^-x)", "tanh(x)", "x squared", "medium"),
 ("What is a batch size?", "Number of samples processed before a weight update", "Number of layers", "Number of epochs", "Size of the test set", "medium"),
 ("What is the key mechanism of Transformer models?", "Self-attention", "Convolution only", "Recurrence only", "Clustering", "hard"),
 ("What is transfer learning?", "Reusing a pretrained model for a new task", "Copying data between servers", "Training without data", "Converting models to SQL", "hard"),
],
"NLP": [
 ("What does NLP stand for?", "Natural Language Processing", "Neural Logic Programming", "Network Layer Protocol", "Numeric Language Parsing", "easy"),
 ("What is tokenisation?", "Splitting text into smaller units like words", "Encrypting text", "Translating text", "Counting characters only", "easy"),
 ("What are stop words?", "Very common words often removed, e.g. 'the', 'is'", "Words that stop a program", "Rare technical words", "Punctuation marks", "easy"),
 ("Which task assigns positive/negative labels to text?", "Sentiment analysis", "Image captioning", "Clustering pixels", "Speech synthesis", "easy"),
 ("What does TF-IDF measure?", "Importance of a word in a document relative to a corpus", "Sentence length", "Grammar errors", "Reading time", "medium"),
 ("What are word embeddings?", "Dense vector representations of words", "Lists of synonyms", "Spell-check dictionaries", "Compressed text files", "medium"),
 ("What is Named Entity Recognition?", "Identifying entities like people and places in text", "Translating names", "Counting nouns", "Removing names", "medium"),
 ("What is stemming?", "Reducing words to their root form", "Adding prefixes", "Translating words", "Checking grammar", "medium"),
 ("What does BERT stand for?", "Bidirectional Encoder Representations from Transformers", "Basic Embedding Recurrent Transformer", "Binary Encoded Review Tool", "Bayesian Entity Recognition Technique", "hard"),
 ("What is perplexity used to evaluate?", "How well a language model predicts text", "Image sharpness", "Network speed", "Clustering purity", "hard"),
],
"Computer_Vision": [
 ("What does a convolution layer do in a CNN?", "Extracts local features using filters", "Stores labels", "Sorts pixels", "Compresses files", "easy"),
 ("What is a pixel?", "The smallest unit of a digital image", "A type of camera", "A neural layer", "A colour palette", "easy"),
 ("Which library is widely used for image processing in Python?", "OpenCV", "Flask", "SQLAlchemy", "Requests", "easy"),
 ("What is image classification?", "Assigning a label to an entire image", "Drawing boxes only", "Colouring images", "Resizing images", "easy"),
 ("What does object detection output?", "Bounding boxes with class labels", "A single label only", "A histogram only", "A blurred image", "medium"),
 ("What is pooling used for?", "Downsampling feature maps", "Increasing resolution", "Adding colour", "Labelling data", "medium"),
 ("What is data augmentation in vision?", "Creating modified copies like flips and crops of images", "Deleting images", "Compressing images", "Encrypting images", "medium"),
 ("Which model family is known for real-time object detection?", "YOLO", "BERT", "Word2Vec", "ARIMA", "medium"),
 ("What does IoU measure?", "Overlap between predicted and ground-truth boxes", "Image brightness", "Network latency", "Colour accuracy", "hard"),
 ("What is semantic segmentation?", "Classifying every pixel in an image", "Detecting only faces", "Resizing images", "Compressing video", "hard"),
],
"Data_Engineering": [
 ("What does ETL stand for?", "Extract, Transform, Load", "Evaluate, Test, Launch", "Encode, Transfer, Log", "Export, Translate, Link", "easy"),
 ("Which tool is commonly used for big-data processing?", "Apache Spark", "Notepad", "Figma", "Postman", "easy"),
 ("What is a data warehouse?", "A central store of structured data optimised for analytics", "A physical building for servers only", "A text editor", "A web framework", "easy"),
 ("What is a data pipeline?", "Automated flow moving and transforming data between systems", "A water pipe", "A SQL index", "A chart type", "easy"),
 ("Which tool is popularly used to schedule and orchestrate workflows?", "Apache Airflow", "Photoshop", "Tableau", "Excel", "medium"),
 ("What is Kafka mainly used for?", "Streaming event data", "Image editing", "Spell checking", "Machine translation", "medium"),
 ("What is the difference between ETL and ELT?", "ELT loads raw data first, then transforms in the warehouse", "They are the same", "ELT never transforms", "ETL never loads", "medium"),
 ("What file format is columnar and common in analytics?", "Parquet", "TXT", "DOCX", "PNG", "medium"),
 ("What is data partitioning?", "Dividing a dataset into segments for performance", "Deleting duplicates", "Encrypting columns", "Renaming tables", "hard"),
 ("What is idempotency in pipelines?", "Re-running a job produces the same result without duplicates", "Jobs run only once ever", "Jobs never fail", "Data is never stored", "hard"),
],
"Cyber_Security": [
 ("What does phishing try to do?", "Trick users into revealing sensitive information", "Speed up networks", "Encrypt files", "Back up data", "easy"),
 ("What does a firewall do?", "Filters network traffic based on rules", "Stores passwords", "Compiles code", "Edits photos", "easy"),
 ("What is two-factor authentication?", "Using two different proofs of identity to log in", "Using two passwords of the same type", "Logging in twice", "Sharing accounts", "easy"),
 ("What does HTTPS provide over HTTP?", "Encrypted communication using TLS", "Faster downloads only", "Free hosting", "Bigger pages", "easy"),
 ("What is SQL injection?", "Inserting malicious SQL through user input", "Optimising SQL queries", "Backing up databases", "Joining tables", "medium"),
 ("What is XSS?", "Injecting malicious scripts into web pages viewed by others", "Encrypting scripts", "A CSS framework", "A server language", "medium"),
 ("Why are passwords salted before hashing?", "To make identical passwords produce different hashes", "To make them shorter", "To make them readable", "To speed up login", "medium"),
 ("What is the principle of least privilege?", "Users get only the access they need", "Everyone is admin", "No one has access", "Access is random", "medium"),
 ("What is a zero-day vulnerability?", "A flaw unknown to the vendor with no patch yet", "A bug fixed in one day", "A virus that expires", "A hardware fault", "hard"),
 ("What does CSRF exploit?", "A user's authenticated session to perform unwanted actions", "Weak Wi-Fi only", "Disk errors", "CPU speed", "hard"),
],
"Git": [
 ("Which command creates a new Git repository?", "git init", "git start", "git new", "git create", "easy"),
 ("Which command stages all changes?", "git add .", "git commit .", "git push .", "git stage-all", "easy"),
 ("Which command downloads a remote repository?", "git clone", "git pull-all", "git fetch-repo", "git copy", "easy"),
 ("What does git commit do?", "Saves staged changes to the local history", "Uploads to GitHub", "Deletes a branch", "Creates a remote", "easy"),
 ("What does git pull do?", "Fetches and merges remote changes", "Deletes local files", "Creates a tag", "Shows history only", "medium"),
 ("What is a branch?", "An independent line of development", "A backup server", "A file type", "A commit message", "medium"),
 ("What does git merge do?", "Combines changes from one branch into another", "Deletes a branch", "Reverts all commits", "Renames a repo", "medium"),
 ("Which command shows commit history?", "git log", "git history-show", "git list", "git past", "medium"),
 ("What does git rebase do?", "Reapplies commits on top of another base commit", "Deletes remote branches", "Creates a fork", "Compresses the repo", "hard"),
 ("What does git stash do?", "Temporarily shelves uncommitted changes", "Permanently deletes changes", "Pushes changes", "Creates a tag", "hard"),
],
"System_Design": [
 ("What does a load balancer do?", "Distributes traffic across multiple servers", "Stores data permanently", "Compiles code", "Encrypts disks", "easy"),
 ("What is caching used for?", "Storing frequently used data for faster access", "Deleting old data", "Encrypting data", "Compiling data", "easy"),
 ("What is horizontal scaling?", "Adding more machines", "Adding more RAM to one machine", "Upgrading the CPU only", "Reducing servers", "easy"),
 ("What is a CDN?", "A network of servers delivering content close to users", "A database type", "A programming language", "A password manager", "easy"),
 ("What is a message queue used for?", "Decoupling services with asynchronous communication", "Styling pages", "Sorting arrays", "Compiling code", "medium"),
 ("What is database replication?", "Copying data across multiple database servers", "Deleting duplicate rows", "Encrypting tables", "Compressing backups", "medium"),
 ("What is a single point of failure?", "A component whose failure brings down the whole system", "A very fast server", "A security feature", "A type of cache", "medium"),
 ("What does rate limiting protect against?", "Excessive requests overloading a service", "Slow disks", "Typos in code", "Merge conflicts", "medium"),
 ("What is the trade-off in CAP theorem during a network partition?", "Choose between consistency and availability", "Choose between CPU and RAM", "Choose between SQL and Python", "Choose between HTTP and HTTPS", "hard"),
 ("What is a microservices architecture?", "An application built as small independently deployable services", "A single large codebase", "A type of database", "A front-end framework", "hard"),
],
"REST_APIs": [
 ("Which HTTP method is typically used to retrieve data?", "GET", "POST", "PUT", "DELETE", "easy"),
 ("What does REST stand for?", "Representational State Transfer", "Remote Server Transfer", "Rapid Endpoint Service Tool", "Relational State Table", "easy"),
 ("Which status code means 'Not Found'?", "404", "200", "500", "301", "easy"),
 ("Which data format is most common in REST APIs?", "JSON", "BMP", "MP3", "EXE", "easy"),
 ("Which HTTP method creates a new resource?", "POST", "GET", "HEAD", "OPTIONS", "medium"),
 ("What does status code 201 mean?", "Resource created", "Unauthorized", "Server error", "Redirect", "medium"),
 ("What does 'stateless' mean in REST?", "Each request contains all information needed to process it", "Server stores session forever", "No database is used", "No authentication", "medium"),
 ("What is the difference between PUT and PATCH?", "PUT replaces a resource; PATCH partially updates it", "They are identical", "PATCH deletes", "PUT only reads", "medium"),
 ("What is idempotency of an HTTP method?", "Repeating the request gives the same server state", "The request is encrypted", "The request is cached forever", "The request is asynchronous", "hard"),
 ("What does CORS control?", "Which origins can access resources from a browser", "Database speed", "Image size", "Compile order", "hard"),
],
"Agile": [
 ("What is a sprint in Scrum?", "A time-boxed iteration to deliver work", "A daily bug", "A type of test", "A release name", "easy"),
 ("Who prioritises the product backlog in Scrum?", "Product Owner", "Scrum Master", "Developers only", "QA team", "easy"),
 ("What is the Agile Manifesto about?", "Valuing individuals, working software, collaboration and responding to change", "Strict documentation", "Fixed contracts", "Waterfall phases", "easy"),
 ("What is a daily stand-up?", "A short daily team sync", "A weekly report", "A performance review", "A code freeze", "easy"),
 ("What is a user story?", "A short description of a feature from the user's perspective", "A bug report", "A database schema", "A test script", "medium"),
 ("What is the purpose of a retrospective?", "Reflect and improve the team's process", "Plan the release date", "Hire new members", "Write documentation", "medium"),
 ("What is Kanban's key practice?", "Visualising work and limiting work in progress", "Fixed-length sprints", "Daily deployment only", "Waterfall phases", "medium"),
 ("What is velocity?", "Amount of work a team completes per sprint", "Server response time", "Typing speed", "Number of meetings", "medium"),
 ("What does 'Definition of Done' provide?", "A shared checklist for when work is complete", "A list of bugs", "A sprint length", "A salary scale", "hard"),
 ("What is technical debt?", "Cost of future rework caused by quick, suboptimal solutions", "Money owed to vendors", "Unused licences", "Server rental cost", "hard"),
],
"Business_Intelligence": [
 ("What is the main goal of Business Intelligence?", "Turn data into insights for decisions", "Write code faster", "Design logos", "Manage hardware", "easy"),
 ("Which tool is a popular BI/dashboard tool?", "Power BI", "Notepad", "Git", "Docker", "easy"),
 ("What is a KPI?", "Key Performance Indicator", "Key Process Integration", "Known Program Input", "Knowledge Payment Index", "easy"),
 ("What is a dashboard?", "A visual display of key metrics", "A type of database", "A programming language", "A server", "easy"),
 ("What is a data warehouse used for in BI?", "Storing integrated historical data for analysis", "Writing emails", "Hosting websites", "Compiling code", "medium"),
 ("What does OLAP allow?", "Multi-dimensional analysis of data", "Image editing", "Real-time chat", "Code compilation", "medium"),
 ("Which chart is best to show a trend over time?", "Line chart", "Pie chart", "Scatter of names", "Table of IDs", "medium"),
 ("What is data cleaning?", "Fixing or removing incorrect, duplicate or incomplete data", "Washing hardware", "Deleting dashboards", "Encrypting data", "medium"),
 ("What is a star schema?", "A fact table linked to dimension tables", "A single flat file", "A network diagram", "A graph database", "hard"),
 ("What is drill-down?", "Navigating from summary data to more detailed data", "Deleting records", "Exporting to PDF", "Changing colours", "hard"),
],
"Technical_Writing": [
 ("What is the main goal of technical writing?", "Communicate complex information clearly", "Entertain readers", "Sell products aggressively", "Write fiction", "easy"),
 ("Who should you write for first?", "Your target audience", "Yourself only", "Competitors", "Search engines only", "easy"),
 ("Which style is preferred in instructions?", "Active voice and short sentences", "Long passive sentences", "Slang", "Jargon-heavy paragraphs", "easy"),
 ("What is an API reference document?", "Documentation listing endpoints, parameters and responses", "A marketing brochure", "A meeting agenda", "A resume", "easy"),
 ("Why use numbered lists for procedures?", "To show the sequence of steps clearly", "To make text longer", "To add decoration", "To hide steps", "medium"),
 ("What is a style guide?", "A set of writing and formatting standards", "A fashion catalogue", "A coding editor", "A database", "medium"),
 ("What is 'docs-as-code'?", "Writing documentation with the same tools and workflow as code", "Documents with no text", "Printing code", "Converting docs to binary", "medium"),
 ("What makes a good README?", "Purpose, install steps, usage and examples", "Only the author's name", "Only licence text", "Private passwords", "medium"),
 ("What is plain language?", "Clear wording the audience can understand easily", "Using only nouns", "Avoiding all numbers", "Writing in capitals", "hard"),
 ("Why include examples in documentation?", "They show real usage and reduce misunderstanding", "They lengthen the page", "They replace explanations always", "They confuse readers", "hard"),
],
"Communication": [
 ("What is active listening?", "Fully concentrating, understanding and responding to the speaker", "Waiting to talk", "Interrupting often", "Checking the phone", "easy"),
 ("Which is non-verbal communication?", "Body language", "Email text", "Phone call words", "Written report", "easy"),
 ("What makes a message clear?", "Simple words and a focused point", "Long unrelated details", "Complex jargon", "Vague phrasing", "easy"),
 ("Why ask clarifying questions?", "To confirm understanding and avoid mistakes", "To delay work", "To show superiority", "To end the meeting", "easy"),
 ("What is constructive feedback?", "Specific, respectful input aimed at improvement", "Personal criticism", "Silent disapproval", "Public blame", "medium"),
 ("What is empathy in communication?", "Understanding and acknowledging another person's feelings", "Agreeing with everything", "Giving orders", "Ignoring emotions", "medium"),
 ("What is the best way to handle a disagreement with a teammate?", "Discuss calmly, focus on the issue and seek common ground", "Avoid them forever", "Escalate immediately", "Argue publicly", "medium"),
 ("When presenting to non-technical stakeholders you should:", "Avoid unnecessary jargon and focus on impact", "Use as much jargon as possible", "Read slides word for word", "Skip the conclusion", "medium"),
 ("What does 'tailoring the message to the audience' mean?", "Adjusting content, tone and detail to who is listening", "Using one message for all", "Making it longer", "Using humour only", "hard"),
 ("What is the purpose of a status update?", "Inform stakeholders of progress, risks and next steps", "Hide problems", "Replace all meetings", "Assign blame", "hard"),
],
}
